# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LushKit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LushKit
  pod 'UIColor_Hex_Swift', '~> 3.0.2'

  target 'LushKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LushKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
