# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LushKit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LushKit
  pod 'UIColor_Hex_Swift', '~> 3.0.2'
  pod 'AutoLayoutHelperSwift', '~> 1.0.2'
  pod 'FormValidatorSwift', '~> 1.0'

  target 'LushKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LushKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end

end
